env:
  global:
    - CXX=g++-4.8

language: node_js
dist: xenial

services:
  - redis

node_js:
  - "12"

script:
  - npm run ci

deploy:
  - provider: npm
    email: "info@deepstream.io"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true
      node_js: '10'

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
